//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS_RDLC_Reports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaOffice
    {
        public int AreaOfficeCode { get; set; }
        public string AreaOfficeName { get; set; }
    }
}
