//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS_RDLC_Reports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientMaster()
        {
            this.CMAT_PC = new HashSet<CMAT_PC>();
            this.Status = new HashSet<Status>();
        }
    
        public int MasterID { get; set; }
        public Nullable<int> ScreeningID { get; set; }
        public Nullable<bool> DataLoad { get; set; }
        public Nullable<bool> isReferral { get; set; }
        public Nullable<bool> isAttestation { get; set; }
        public Nullable<bool> isCMAT { get; set; }
        public Nullable<bool> isMFC { get; set; }
        public string ReferralSrc { get; set; }
        public string OtherReferralSrc { get; set; }
        public string C_Src { get; set; }
        public string OtherCMATSrc { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public Nullable<System.DateTime> A_DateReceived { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MI { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string SSN { get; set; }
        public string MedicaidID { get; set; }
        public string KidCareID { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> EmailConsent { get; set; }
        public string EmailAddress { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string PreferredLanguage { get; set; }
        public string HealthPlanProvider { get; set; }
        public string HealthPlanNumber { get; set; }
        public string PlanProviderNumber { get; set; }
        public string CaseNo { get; set; }
        public string PCPTaxID { get; set; }
        public string PCPFirstName { get; set; }
        public string PCPLastName { get; set; }
        public string PGFirstName { get; set; }
        public string PGLastName { get; set; }
        public string PMI { get; set; }
        public string PGPhone { get; set; }
        public string CMSQuestion1 { get; set; }
        public string CMSQuestion2 { get; set; }
        public string CMSQuestion3 { get; set; }
        public Nullable<int> SpecialNeedCode1 { get; set; }
        public Nullable<int> SpecialNeedCode2 { get; set; }
        public Nullable<int> SpecialNeedCode3 { get; set; }
        public string SpecialNeedNotes { get; set; }
        public Nullable<bool> DoNotCall { get; set; }
        public string MMI { get; set; }
        public string OtherID { get; set; }
        public string OtherIDType { get; set; }
        public Nullable<bool> Resend { get; set; }
        public Nullable<System.DateTime> ResponseSentDate { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> R_OptOut { get; set; }
        public Nullable<bool> A_OptOut { get; set; }
        public Nullable<int> R_Status { get; set; }
        public string A_Status { get; set; }
        public string R_Attachment { get; set; }
        public string A_Attachment { get; set; }
        public string C_Attachment { get; set; }
        public Nullable<System.DateTime> A_AttScannedDt { get; set; }
        public string A_Init_Rescreen { get; set; }
        public string A_MDName { get; set; }
        public string A_MDMedicaidID { get; set; }
        public string A_PhysGrpName { get; set; }
        public string A_PhysGrpAddr { get; set; }
        public string A_PhysGrpPhone { get; set; }
        public string A_PhysGrpFax { get; set; }
        public string A_PhysGrpContact { get; set; }
        public Nullable<System.DateTime> A_SignDate { get; set; }
        public Nullable<bool> A_MDInitialsYN { get; set; }
        public string A_MedicalReview { get; set; }
        public string A_MedicalLicenseNumber { get; set; }
        public string A_FacilityName { get; set; }
        public string AreaOfficeCode { get; set; }
        public Nullable<bool> Redetermination { get; set; }
        public Nullable<bool> R_CMSEligible { get; set; }
        public Nullable<bool> A_CMSEligible { get; set; }
        public string WorkedBy { get; set; }
        public Nullable<System.DateTime> WorkedDate { get; set; }
        public Nullable<bool> IsDuplicate { get; set; }
        public Nullable<bool> isSDelete { get; set; }
        public Nullable<bool> isEnrolled { get; set; }
        public Nullable<System.DateTime> EnrollmentStartDate { get; set; }
        public Nullable<System.DateTime> EnrollmentEndDate { get; set; }
        public Nullable<System.DateTime> R_ScreeningDt { get; set; }
        public Nullable<System.DateTime> A_ScreeningDt { get; set; }
        public Nullable<bool> isMergedDelete { get; set; }
        public Nullable<int> MergedMasterId { get; set; }
        public Nullable<int> C_PGRelation { get; set; }
        public string C_PGRelation_Other { get; set; }
        public Nullable<bool> isDupAHCAOutbound { get; set; }
        public Nullable<bool> isNotSameE_Outbound { get; set; }
        public Nullable<bool> isHistoryDelete { get; set; }
        public Nullable<bool> isSafetyNet { get; set; }
        public Nullable<bool> isBNet { get; set; }
        public string Phone1Extension { get; set; }
        public string Phone2Extension { get; set; }
        public string PGPhoneExtension { get; set; }
        public string A_PhysGrpPhoneExt { get; set; }
        public string KidCareAccNo { get; set; }
        public string OtherInsuranceName { get; set; }
        public string OtherInsuranceID { get; set; }
        public Nullable<System.DateTime> CmatDeletion_Dt { get; set; }
        public Nullable<bool> isCDelete { get; set; }
        public Nullable<System.DateTime> MfcDeletion_Dt { get; set; }
        public Nullable<bool> isMfcDelete { get; set; }
        public string CMATReOpenReason { get; set; }
        public string MFCReOpenReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMAT_PC> CMAT_PC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Status { get; set; }
    }
}
