//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS_RDLC_Reports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMAT_Assessment
    {
        public int CMAT_AssessmentID { get; set; }
        public int MasterID { get; set; }
        public Nullable<int> CMATID { get; set; }
        public Nullable<int> CMAT_PCID { get; set; }
        public string MedicalSummary { get; set; }
        public string PsychosocialSummary { get; set; }
        public string Agencies { get; set; }
        public Nullable<System.DateTime> GC_DateMeasured { get; set; }
        public Nullable<decimal> GC_AgeMeasured { get; set; }
        public string GC_AgeinYM { get; set; }
        public Nullable<decimal> GC_GestationalAge { get; set; }
        public string GC_GestationalAgeUnit { get; set; }
        public Nullable<decimal> GC_CorrectedAge { get; set; }
        public string GC_CorrectedAgeUnit { get; set; }
        public Nullable<decimal> GC_Height { get; set; }
        public string GC_HeightUnit { get; set; }
        public Nullable<decimal> GC_Weight { get; set; }
        public string GC_WeightUnit { get; set; }
        public Nullable<decimal> GC_HeadCircumference { get; set; }
        public string GC_HeadUnit { get; set; }
        public string GC_BMI { get; set; }
        public string GC_GrowthConcern { get; set; }
        public string GC_OtherGrowthDescription { get; set; }
        public string Nutrition1 { get; set; }
        public string N1_Desc { get; set; }
        public string Nutrition2 { get; set; }
        public string N2_Desc { get; set; }
        public string Nutrition3 { get; set; }
        public string N3_Desc { get; set; }
        public string Nutrition_Other { get; set; }
        public Nullable<System.DateTime> E_OrderedDt { get; set; }
        public string ClinicalSignOff_Name { get; set; }
        public string ClinicalSignOff_Title { get; set; }
        public Nullable<System.DateTime> ClinicalSignOff_Date { get; set; }
        public string PsychosocialSignOff_Name { get; set; }
        public string PsychosocialSignOff_Title { get; set; }
        public Nullable<System.DateTime> PsychosocialSignOff_Date { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public bool isCompleted { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> isSubmitted { get; set; }
        public string WorkedBy { get; set; }
        public Nullable<System.DateTime> WorkedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AmendCount { get; set; }
        public Nullable<bool> IsStaffingDone { get; set; }
        public string A_StaffingType { get; set; }
        public string S_StaffingDt { get; set; }
        public string S_StaffingType { get; set; }
        public string S_StaffingPurpose { get; set; }
        public string S_NursingAssessmentUpdate { get; set; }
        public string S_Discussion { get; set; }
        public string S_TaskList { get; set; }
        public Nullable<int> S_AdditionalConsiderationsID { get; set; }
        public string S_AdditionalOther { get; set; }
        public string S_CC { get; set; }
        public Nullable<System.DateTime> S_NextStaffingDt { get; set; }
        public Nullable<System.DateTime> S_SignOffDate { get; set; }
        public Nullable<int> S_AmendCounter { get; set; }
        public Nullable<bool> S_isAmend { get; set; }
        public Nullable<bool> S_isDraft { get; set; }
        public Nullable<bool> S_isCompleted { get; set; }
        public Nullable<int> MFCID { get; set; }
        public string S_ClinicalSignOff_Name { get; set; }
        public string S_ClinicalSignOff_Title { get; set; }
        public Nullable<System.DateTime> S_ClinicalSignOff_Date { get; set; }
        public string S_PsychosocialSignOff_Name { get; set; }
        public string S_PsychosocialSignOff_Title { get; set; }
        public Nullable<System.DateTime> S_PsychosocialSignOff_Date { get; set; }
        public string A_StaffingDt { get; set; }
        public Nullable<int> SignOffCount { get; set; }
        public Nullable<int> S_SignOffCount { get; set; }
        public Nullable<System.DateTime> S_CompletionDate { get; set; }
        public string S_CurrentStabilityStatement { get; set; }
        public string A_SignOffCompletionBy { get; set; }
        public string S_WorkedBy { get; set; }
        public Nullable<System.DateTime> S_WorkedDt { get; set; }
        public string S_LevelOfCare { get; set; }
        public string S_LevelOfReimbursment { get; set; }
        public string S_Modelwaiver { get; set; }
        public Nullable<int> S_Duration { get; set; }
        public string S_PsychosocialAssessmentUpdate { get; set; }
        public string S_ProgramEligibility { get; set; }
    }
}
